=== Kawa-oneechan/psk/ProjectSpecialK/data/schemas/villager.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"properties": {
		"id": {
			"description": "The internal identification code for this item. Must be unique.",
			"type": "string"
		},
		"name": {
 			"anyOf": [
				{
					"type": "string"
				},
				{
					"type": "array",
					"contains": {
						"type": "string"
					},
					"minContains": 2,
					"maxContains": 2
				},
				{
					"type": "object",
					"minContains": 2,
					"maxContains": 2
				}
			]
		},
		"species": {
			"type": "string"
		},
		"personality": {
			"type": "array",
			"items": {
				"type": "string",
					"minContains": 1
			}
		},
		"personalitySubtype": {
			"type": "number",
				"default": 1
		},
		"gender": {
			"type": "string",
				"pattern": "boy|girl|enby-b|enby-g"
		},
		"attraction": {
			"type": "string",
				"pattern": "boys|girls|both|none"
		},
		"birthday": {
			"oneOf": [
				{
					"type": "string",
					"pattern": "[A-Z][a-z][a-z] [0-9][0-9]"
				},
				{
					"type": "string",
					"pattern": "[0-9][0-9]-[0-9][0-9]"
				},
			{
			"type": "array",
			"minItems": 2,
				"maxItems": 2,
			"items": {
				"type": "number"
			}
			}
				]
		},
		"hobby": {
			"type": "string"
		},
		"colors": {
			"type": "array",
			"minItems": 2,
			"maxItems": 2,
			"items": {
				"type": "string"
			}
		},
		"nameTag": {
			"type": "array",
			"minItems": 2,
			"maxItems": 2,
			"items": {
							"oneOf": [
				{
					"type": "string",
					"pattern": "#([A-F0-9]{6,6})"
				},
				{
					"type": "array",
					"minItems": 3,
					"maxItems": 3,
					"items": {
						"type": "number"
					}
				},
			{
			"type": "array",
			"minItems": 2,
				"maxItems": 2,
			"items": {
				"type": "number"
			}
			}
				]
			}
		},
		"catchphrase": {
			"anyOf": [
				{
					"type": "string"
				},
				{
					"type": "array",
					"contains": {
						"type": "string"
					},
					"minContains": 2,
					"maxContains": 2
				},
				{
					"type": "object",
					"minContains": 2,
					"maxContains": 2
				}
			]
		},
		"clothing": {
			"type": "object",
			"properties": {
				"default": {
					"type": "string"
				},
				"rain": {
					"type": "array",
						"minItems": 2,
							"maxItems": 2,
					"items": {
						"type": "string"
					}
				}
			},
			"required": [
				"default",
				"rain"
			]
		},
		"umbrella": {
			"type": "string"
		},
		"photo": {
			"type": "string"
		},
		"poster": {
			"type": "string"
		},
		"house": {
			"type": "object",
			"properties": {
				"walls": {
					"type": "string"
				},
				"floor": {
					"type": "string"
				},
				"music": {
					"type": "string"
				},
				"items": {
					"type": "array",
					"items": {
						"type": "string"
					}
				}
			},
			"required": [
				"walls",
				"floor",
				"music",
				"items"
			]
		}
	},
	"required": [
		"id",
		"name",
		"species",
		"personality",
		"personalitySubtype",
		"gender",
		"attraction",
		"birthday",
		"hobby",
		"colors",
		"nameTag",
		"catchphrase",
		"clothing",
		"umbrella",
		"photo",
		"poster",
		"house"
	]
}

=== Kawa-oneechan/psk/ProjectSpecialK/data/villagers/psk_cat06/cat06.json
{
  "id" : "psk:cat06",
  "name" : {
    "en" : "Sarta"
  },
  "species" : "cat",
  "personality" : [ "uchi" ],
  "personalitySubtype" : 0,
  "gender" : "fem",
  "attraction" : "both",
  "birthday" : [ 13, 10 ],
  "hobby" : "music",
  "colors" : [ "purple", "blue" ],
  "nameTag" : [ "#FFFFFF", "#848484" ],
  "catchphrase" : {
    "en" : "zipper"
  },
  "clothing" : {
    "default" : "acnh:heartsweater/red",
    "rain" : [ "acnh:raincoat/blue", "acnh:rainhat/blue" ]
  },
  "umbrella" : "acnh:blackchicumbrella",
  "photo" : "psk:sartasphoto",
  "poster" : "psk:sartasposter",
  "house" : {
    "walls" : "acnh:purplerosewall",
    "floor" : "acnh:simpleblueflooring",
    "music" : "acnh:kksonata",
    "items" : [
      "acnh:antiqueminitable",
      "acnh:antiqueconsoletable",
      "acnh:pianobench/1",
      "acnh:antiqueclock",
      "acnh:rattanlowtable/3",
      "acnh:doublesofa/4",
      "acnh:fireplace/1",
      "acnh:phonograph/0/2",
      "acnh:grandpiano/1"
    ]
  }
}

=== Kawa-oneechan/psk/ProjectSpecialK/data/villagers/psk_cat10/cat10.json
{
  "id" : "psk:cat10",
  "name" : {
    "en" : "Danny"
  },
  "species" : "cat",
  "personality" : [ "uchi" ],
  "personalitySubtype" : 0,
  "gender" : "fem",
  "attraction" : "none",
  "birthday" : [ 5, 6 ],
  "hobby" : "nature",
  "colors" : [ "blue", "gray" ],
  "nameTag" : [ "#FFFFFF", "#848484" ],
  "catchphrase" : {
    "en" : "mow wow"
  },
  "clothing" : {
    "default" : "acnh:heartsweater/red",
    "rain" : [ "acnh:raincoat/blue", "acnh:rainhat/blue" ]
  },
  "umbrella" : "acnh:blackchicumbrella",
  "photo" : "psk:velvetsphoto",
  "poster" : "psk:velvetsposter",
  "house" : {
    "walls" : "acnh:purplerosewall",
    "floor" : "acnh:simpleblueflooring",
    "music" : "acnh:kksonata",
    "items" : [
      "acnh:antiqueminitable",
      "acnh:antiqueconsoletable",
      "acnh:pianobench/1",
      "acnh:antiqueclock",
      "acnh:rattanlowtable/3",
      "acnh:doublesofa/4",
      "acnh:fireplace/1",
      "acnh:phonograph/0/2",
      "acnh:grandpiano/1"
    ]
  }
}

=== Kawa-oneechan/psk/ProjectSpecialK/data/villagers/psk/cat03/cat03.json
{
  "id" : "psk:cat03",
  "name" : {
    "en" : "Bea"
  },
  "species" : "cat",
  "personality" : [ "snooty" ],
  "personalitySubtype" : 0,
  "gender" : "fnb",
  "attraction" : "boys",
  "birthday" : [ 4, 10 ],
  "hobby" : "education",
  "colors" : [ "black", "yellow" ],
  "nameTag" : [ "#FFFFFF", "#848484" ],
  "catchphrase" : {
    "en" : "hyahaha"
  },
  "clothing" : {
    "default" : "acnh:heartsweater/red",
    "rain" : [ "acnh:raincoat/blue", "acnh:rainhat/blue" ]
  },
  "umbrella" : "acnh:redumbrella",
  "photo" : "psk:beasphoto",
  "poster" : "psk:beasposter",
  "house" : {
    "walls" : "acnh:commonwall",
    "floor" : "acnh:commonflooring",
    "music" : "acnh:silence",
    "items" : [
    ]
  }
}

=== Kawa-oneechan/psk/ProjectSpecialK/mods/fnaf/villagers/fnaf03/fnaf03.json
{
  "id" : "fnaf:fnaf03",
  "name" : {
    "en" : "Roxanne"
  },
  "species" : "wol",
  "personality" : [ "weird" ],
  "personalitySubtype" : 0,
  "gender" : "girl",
  "attraction" : "both",
  "birthday" : [ 1, 1 ],
  "hobby" : "music",
  "colors" : [ "red", "green" ],
  "nameTag" : [ "#FFFFFF", "#848484" ],
  "catchphrase" : {
    "en" : "rockstar"
  },
  "clothing" : {
    "default" : "acnh:heartsweater/red",
    "rain" : [ "acnh:raincoat/blue", "acnh:rainhat/blue" ]
  },
  "umbrella" : "acnh:redumbrella",
  "photo" : "fnaf:roxannesphoto",
  "poster" : "fnaf:roxannesposter",
  "house" : {
    "walls" : "acnh:commonwall",
    "floor" : "acnh:commonflooring",
    "music" : "acnh:silence",
    "items" : [
    ]
  }
}

=== Kawa-oneechan/psk/ProjectSpecialK/data/villagers/psk_cat05/cat05.json
{
  "id" : "psk:cat05",
  "name" : {
    "en" : "Felix"
  },
  "species" : "cat",
  "personality" : [ "jock" ],
  "personalitySubtype" : 0,
  "gender" : "mas",
  "attraction" : "both",
  "birthday" : [ 25, 11 ],
  "hobby" : "music",
  "colors" : [ "red", "purple" ],
  "nameTag" : [ "#FFFFFF", "#848484" ],
  "catchphrase" : {
    "en" : "excellent"
  },
  "clothing" : {
    "default" : "acnh:heartsweater/red",
    "rain" : [ "acnh:raincoat/blue", "acnh:rainhat/blue" ]
  },
  "umbrella" : "acnh:blackchicumbrella",
  "photo" : "psk:felixsphoto",
  "poster" : "psk:felixsposter",
  "house" : {
    "walls" : "acnh:purplerosewall",
    "floor" : "acnh:simpleblueflooring",
    "music" : "acnh:kksonata",
    "items" : [
      "acnh:antiqueminitable",
      "acnh:antiqueconsoletable",
      "acnh:pianobench/1",
      "acnh:antiqueclock",
      "acnh:rattanlowtable/3",
      "acnh:doublesofa/4",
      "acnh:fireplace/1",
      "acnh:phonograph/0/2",
      "acnh:grandpiano/1"
    ]
  }
}

=== Kawa-oneechan/psk/ProjectSpecialK/data/villagers/psk_cat11/cat11.json
{
  "id" : "psk:cat11",
  "name" : {
    "en" : "Rockie"
  },
  "species" : "cat",
  "personality" : [ "peppy" ],
  "personalitySubtype" : 0,
  "gender" : "fem",
  "attraction" : "both",
  "birthday" : [ 9, 6 ],
  "hobby" : "music",
  "colors" : [ "pink", "yellow" ],
  "nameTag" : [ "#FFFFFF", "#848484" ],
  "catchphrase" : {
    "en" : "kakeen~"
  },
  "clothing" : {
    "default" : "acnh:heartsweater/red",
    "rain" : [ "acnh:raincoat/blue", "acnh:rainhat/blue" ]
  },
  "umbrella" : "acnh:blackchicumbrella",
  "photo" : "psk:velvetsphoto",
  "poster" : "psk:velvetsposter",
  "house" : {
    "walls" : "acnh:purplerosewall",
    "floor" : "acnh:simpleblueflooring",
    "music" : "acnh:kksonata",
    "items" : [
      "acnh:antiqueminitable",
      "acnh:antiqueconsoletable",
      "acnh:pianobench/1",
      "acnh:antiqueclock",
      "acnh:rattanlowtable/3",
      "acnh:doublesofa/4",
      "acnh:fireplace/1",
      "acnh:phonograph/0/2",
      "acnh:grandpiano/1"
    ]
  }
}

=== Kawa-oneechan/psk/ProjectSpecialK/mods/fnaf/villagers/fnaf01/fnaf01.json
{
  "id" : "fnaf:fnaf01",
  "name" : {
    "en" : "Bonnie"
  },
  "species" : "rbt",
  "personality" : [ "plain" ],
  "personalitySubtype" : 0,
  "gender" : "boy",
  "attraction" : "none",
  "birthday" : [ 1, 1 ],
  "hobby" : "music",
  "colors" : [ "blue", "purple" ],
  "nameTag" : [ "#FFFFFF", "#848484" ],
  "catchphrase" : {
    "en" : "superstar"
  },
  "clothing" : {
    "default" : "acnh:heartsweater/red",
    "rain" : [ "acnh:raincoat/blue", "acnh:rainhat/blue" ]
  },
  "umbrella" : "acnh:redumbrella",
  "photo" : "fnaf:bonniesphoto",
  "poster" : "fnaf:bonniesposter",
  "house" : {
    "walls" : "acnh:commonwall",
    "floor" : "acnh:commonflooring",
    "music" : "acnh:silence",
    "items" : [
    ]
  }
}

=== Kawa-oneechan/psk/ProjectSpecialK/data/villagers/psk_cat03/cat03.json
{
  "id" : "psk:cat03",
  "name" : {
    "en" : "Meiki"
  },
  "species" : "cat",
  "personality" : [ "normal" ],
  "personalitySubtype" : 0,
  "gender" : "fnb",
  "attraction" : "none",
  "birthday" : [ 22, 7 ],
  "hobby" : "play",
  "colors" : [ "white", "yellow" ],
  "nameTag" : [ "#AA6405", "#FFF7CF" ],
  "catchphrase" : {
    "en" : "I think"
  },
  "clothing" : {
    "default" : "acnh:heartsweater/red",
    "rain" : [ "acnh:raincoat/blue", "acnh:rainhat/blue" ]
  },
  "umbrella" : "acnh:blackchicumbrella",
  "photo" : "psk:meikisphoto",
  "poster" : "psk:meikisposter",
  "house" : {
    "walls" : "acnh:purplerosewall",
    "floor" : "acnh:simpleblueflooring",
    "music" : "acnh:kksonata",
    "items" : [
      "acnh:antiqueminitable",
      "acnh:antiqueconsoletable",
      "acnh:pianobench/1",
      "acnh:antiqueclock",
      "acnh:rattanlowtable/3",
      "acnh:doublesofa/4",
      "acnh:fireplace/1",
      "acnh:phonograph/0/2",
      "acnh:grandpiano/1"
    ]
  }
}
