=== Kawa-oneechan/psk/ProjectSpecialK/data/schemas/villager.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"properties": {
		"id": {
			"description": "The internal identification code for this item. Must be unique.",
			"type": "string"
		},
		"name": {
 			"anyOf": [
				{
					"type": "string"
				},
				{
					"type": "array",
					"contains": {
						"type": "string"
					},
					"minContains": 2,
					"maxContains": 2
				},
				{
					"type": "object",
					"minContains": 2,
					"maxContains": 2
				}
			]
		},
		"species": {
			"type": "string"
		},
		"personality": {
			"type": "array",
			"items": {
				"type": "string",
					"minContains": 1
			}
		},
		"personalitySubtype": {
			"type": "number",
				"default": 1
		},
		"gender": {
			"type": "string",
				"pattern": "boy|girl|enby-b|enby-g"
		},
		"attraction": {
			"type": "string",
				"pattern": "boys|girls|both|none"
		},
		"birthday": {
			"oneOf": [
				{
					"type": "string",
					"pattern": "[A-Z][a-z][a-z] [0-9][0-9]"
				},
				{
					"type": "string",
					"pattern": "[0-9][0-9]-[0-9][0-9]"
				},
			{
			"type": "array",
			"minItems": 2,
				"maxItems": 2,
			"items": {
				"type": "number"
			}
			}
				]
		},
		"hobby": {
			"type": "string"
		},
		"colors": {
			"type": "array",
			"minItems": 2,
			"maxItems": 2,
			"items": {
				"type": "string"
			}
		},
		"nameTag": {
			"type": "array",
			"minItems": 2,
			"maxItems": 2,
			"items": {
							"oneOf": [
				{
					"type": "string",
					"pattern": "#([A-F0-9]{6,6})"
				},
				{
					"type": "array",
					"minItems": 3,
					"maxItems": 3,
					"items": {
						"type": "number"
					}
				},
			{
			"type": "array",
			"minItems": 2,
				"maxItems": 2,
			"items": {
				"type": "number"
			}
			}
				]
			}
		},
		"catchphrase": {
			"anyOf": [
				{
					"type": "string"
				},
				{
					"type": "array",
					"contains": {
						"type": "string"
					},
					"minContains": 2,
					"maxContains": 2
				},
				{
					"type": "object",
					"minContains": 2,
					"maxContains": 2
				}
			]
		},
		"clothing": {
			"type": "object",
			"properties": {
				"default": {
					"type": "string"
				},
				"rain": {
					"type": "array",
						"minItems": 2,
							"maxItems": 2,
					"items": {
						"type": "string"
					}
				}
			},
			"required": [
				"default",
				"rain"
			]
		},
		"umbrella": {
			"type": "string"
		},
		"photo": {
			"type": "string"
		},
		"poster": {
			"type": "string"
		},
		"house": {
			"type": "object",
			"properties": {
				"walls": {
					"type": "string"
				},
				"floor": {
					"type": "string"
				},
				"music": {
					"type": "string"
				},
				"items": {
					"type": "array",
					"items": {
						"type": "string"
					}
				}
			},
			"required": [
				"walls",
				"floor",
				"music",
				"items"
			]
		}
	},
	"required": [
		"id",
		"name",
		"species",
		"personality",
		"personalitySubtype",
		"gender",
		"attraction",
		"birthday",
		"hobby",
		"colors",
		"nameTag",
		"catchphrase",
		"clothing",
		"umbrella",
		"photo",
		"poster",
		"house"
	]
}

=== Kawa-oneechan/psk/ProjectSpecialK/data/villagers/psk_cat08/cat08.json
{
  "id" : "psk:cat08",
  "name" : {
    "en" : "Semilina"
  },
  "species" : "cat",
  "personality" : [ "uchi" ],
  "personalitySubtype" : 0,
  "gender" : "fem",
  "attraction" : "none",
  "birthday" : [ 2, 7 ],
  "hobby" : "nature",
  "colors" : [ "colorful", "white" ],
  "nameTag" : [ "#FFFFFF", "#848484" ],
  "catchphrase" : {
    "en" : "mrow"
  },
  "clothing" : {
    "default" : "acnh:heartsweater/red",
    "rain" : [ "acnh:raincoat/blue", "acnh:rainhat/blue" ]
  },
  "umbrella" : "acnh:blackchicumbrella",
  "photo" : "psk:semilinasphoto",
  "poster" : "psk:semilinasposter",
  "house" : {
    "walls" : "acnh:purplerosewall",
    "floor" : "acnh:simpleblueflooring",
    "music" : "acnh:kksonata",
    "items" : [
      "acnh:antiqueminitable",
      "acnh:antiqueconsoletable",
      "acnh:pianobench/1",
      "acnh:antiqueclock",
      "acnh:rattanlowtable/3",
      "acnh:doublesofa/4",
      "acnh:fireplace/1",
      "acnh:phonograph/0/2",
      "acnh:grandpiano/1"
    ]
  }
}

=== Kawa-oneechan/psk/ProjectSpecialK/data/villagers/psk/cat09/cat09.json
{
	"id": "psk:cat09",
	"name": {
		"en": "Danny"
	},
	"species": "cat",
	"personality": [ "uchi" ],
	"personalitySubtype": 0,
	"gender": "girl",
	"attraction": "none",
	"birthday": [ 5, 6 ],
	"hobby": "nature",
	"colors": [ "blue", "gray" ],
	"nameTag": [ "#FFFFFF", "#848484" ],
	"catchphrase": {
		"en": "mow wow"
	},
	"clothing": {
		"default": "acnh:heartsweater/red",
		"rain": [ "acnh:raincoat/blue", "acnh:rainhat/blue" ]
	},
	"umbrella": "acnh:redumbrella",
	"photo": "psk:velvetsphoto",
	"poster": "psk:velvetsposter",
	"house": {
		"walls": "acnh:commonwall",
		"floor": "acnh:commonflooring",
		"music": "acnh:silence",
		"items": [
		]
	}
}

=== Kawa-oneechan/psk/ProjectSpecialK/data/villagers/psk_cat01/cat01.json
{
  "id" : "psk:cat01",
  "name" : {
    "en" : "Jasmine",
    "ja" : "ジャスミン",
    "ko" : "재스민",
    "zh" : "茉莉",
    "de" : "Jasmin",
    "ru" : "Жасмин",
    "nl" : "Jasmijn",
    "hu" : "Jázmin"
  },
  "species" : "cat",
  "personality" : [ "horny", "uchi" ],
  "personalitySubtype" : 0,
  "gender" : "fem",
  "attraction" : "both",
  "birthday" : [ 3, 2 ],
  "hobby" : "music",
  "colors" : [ "white", "black" ],
  "nameTag" : [ "#FFFFFF", "#848484" ],
  "catchphrase" : {
    "en" : "mmmmrr",
    "ja" : "うーん",
    "ru" : "ммммрр"
  },
  "clothing" : {
    "default" : "acnh:heartsweater/red",
    "rain" : [ "acnh:raincoat/blue", "acnh:rainhat/blue" ]
  },
  "umbrella" : "acnh:blackchicumbrella",
  "photo" : "acnh:jasminesphoto",
  "poster" : "acnh:jasminesposter",
  "house" : {
    "walls" : "acnh:purplerosewall",
    "floor" : "acnh:simpleblueflooring",
    "music" : "acnh:kksonata",
    "items" : [
      "acnh:antiqueminitable",
      "acnh:antiqueconsoletable",
      "acnh:pianobench/1",
      "acnh:antiqueclock",
      "acnh:rattanlowtable/3",
      "acnh:doublesofa/4",
      "acnh:fireplace/1",
      "acnh:phonograph/0/2",
      "acnh:grandpiano/1"
    ]
  }
}

=== Kawa-oneechan/psk/ProjectSpecialK/data/villagers/psk_cat07/cat07.json
{
  "id" : "psk:cat07",
  "name" : {
    "en" : "Socks"
  },
  "species" : "cat",
  "personality" : [ "cranky" ],
  "personalitySubtype" : 0,
  "gender" : "mnb",
  "attraction" : "both",
  "birthday" : [ 21, 12 ],
  "hobby" : "music",
  "colors" : [ "green", "blue" ],
  "nameTag" : [ "#FFFFFF", "#848484" ],
  "catchphrase" : {
    "en" : "y'know dude"
  },
  "clothing" : {
    "default" : "acnh:heartsweater/red",
    "rain" : [ "acnh:raincoat/blue", "acnh:rainhat/blue" ]
  },
  "umbrella" : "acnh:blackchicumbrella",
  "photo" : "psk:socksphoto",
  "poster" : "psk:socksposter",
  "house" : {
    "walls" : "acnh:purplerosewall",
    "floor" : "acnh:simpleblueflooring",
    "music" : "acnh:kksonata",
    "items" : [
      "acnh:antiqueminitable",
      "acnh:antiqueconsoletable",
      "acnh:pianobench/1",
      "acnh:antiqueclock",
      "acnh:rattanlowtable/3",
      "acnh:doublesofa/4",
      "acnh:fireplace/1",
      "acnh:phonograph/0/2",
      "acnh:grandpiano/1"
    ]
  }
}

=== Kawa-oneechan/psk/ProjectSpecialK/mods/fnaf/villagers/fnaf02/fnaf02.json
{
  "id" : "fnaf:fnaf02",
  "name" : {
    "en" : "Chica"
  },
  "species" : "chn",
  "personality" : [ "weird" ],
  "personalitySubtype" : 0,
  "gender" : "girl",
  "attraction" : "both",
  "birthday" : [ 1, 1 ],
  "hobby" : "music",
  "colors" : [ "pink", "green" ],
  "nameTag" : [ "#FFFFFF", "#848484" ],
  "catchphrase" : {
    "en" : "pizza"
  },
  "clothing" : {
    "default" : "acnh:heartsweater/red",
    "rain" : [ "acnh:raincoat/blue", "acnh:rainhat/blue" ]
  },
  "umbrella" : "acnh:redumbrella",
  "photo" : "fnaf:chicasphoto",
  "poster" : "fnaf:chicasposter",
  "house" : {
    "walls" : "acnh:commonwall",
    "floor" : "acnh:commonflooring",
    "music" : "acnh:silence",
    "items" : [
    ]
  }
}

=== Kawa-oneechan/psk/ProjectSpecialK/data/villagers/psk/cat10/cat10.json
{
  "id" : "psk:cat10",
  "name" : {
    "en" : "Rockie"
  },
  "species" : "cat",
  "personality" : [ "peppy" ],
  "personalitySubtype" : 0,
  "gender" : "fem",
  "attraction" : "both",
  "birthday" : [ 9, 6 ],
  "hobby" : "music",
  "colors" : [ "pink", "yellow" ],
  "nameTag" : [ "#FFFFFF", "#848484" ],
  "catchphrase" : {
    "en" : "kakeen~"
  },
  "clothing" : {
    "default" : "acnh:heartsweater/red",
    "rain" : [ "acnh:raincoat/blue", "acnh:rainhat/blue" ]
  },
  "umbrella" : "acnh:redumbrella",
  "photo" : "psk:velvetsphoto",
  "poster" : "psk:velvetsposter",
  "house" : {
    "walls" : "acnh:commonwall",
    "floor" : "acnh:commonflooring",
    "music" : "acnh:silence",
    "items" : [
    ]
  }
}

=== Kawa-oneechan/psk/ProjectSpecialK/data/villagers/psk_cat02/cat02.json
{
  "id" : "psk:cat02",
  "name" : {
    "en" : "Farrah"
  },
  "species" : "cat",
  "personality" : [ "normal" ],
  "personalitySubtype" : 0,
  "gender" : "fem",
  "attraction" : "both",
  "birthday" : [ 3, 2 ],
  "hobby" : "fitness",
  "colors" : [ "white", "black" ],
  "nameTag" : [ "#FFFFFF", "#848484" ],
  "catchphrase" : {
    "en" : ""
  },
  "clothing" : {
    "default" : "acnh:heartsweater/red",
    "rain" : [ "acnh:raincoat/blue", "acnh:rainhat/blue" ]
  },
  "umbrella" : "acnh:blackchicumbrella",
  "photo" : "acnh:farrahsphoto",
  "poster" : "acnh:farrahsposter",
  "house" : {
    "walls" : "acnh:purplerosewall",
    "floor" : "acnh:simpleblueflooring",
    "music" : "acnh:kksonata",
    "items" : [
      "acnh:antiqueminitable",
      "acnh:antiqueconsoletable",
      "acnh:pianobench/1",
      "acnh:antiqueclock",
      "acnh:rattanlowtable/3",
      "acnh:doublesofa/4",
      "acnh:fireplace/1",
      "acnh:phonograph/0/2",
      "acnh:grandpiano/1"
    ]
  }
}

=== Kawa-oneechan/psk/ProjectSpecialK/data/villagers/psk/cat02/cat02.json
{
	"id": "psk:cat02",
	"name": {
		"en": "Meiki"
	},
	"species": "cat",
	"personality": [ "normal" ],
	"personalitySubtype": 0,
	"gender": "enby-g",
	"attraction": "none",
	"birthday": [ 22, 7 ],
	"hobby": "play",
	"colors": [ "white", "yellow" ],
	"nameTag": [ "#AA6405", "#FFF7CF" ],
	"catchphrase": {
		"en": "I think"
	},
	"clothing": {
		"default": "acnh:heartsweater/red",
		"rain": [ "acnh:raincoat/blue", "acnh:rainhat/blue" ]
	},
	"umbrella": "acnh:redumbrella",
	"photo": "psk:meikisphoto",
	"poster": "psk:meikisposter",
	"house": {
		"walls": "acnh:commonwall",
		"floor": "acnh:commonflooring",
		"music": "acnh:silence",
		"items": [
		]
	}
}
